package com.enMedio.Model;
// Generated 18/07/2021 09:58:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Calificacion generated by hbm2java
 */
@Entity
@Table(name="calificacion"
    ,catalog="pruebaenmedio"
)
public class Calificacion  implements java.io.Serializable {


     private Integer id;
     private Clientes clientes;
     private Productos productos;
     private Integer calificacion;
     private String observacion;

    public Calificacion() {
    }

	
    public Calificacion(Integer id, Clientes clientes, Productos productos, Integer calificacion) {
        this.id = id;
        this.clientes = clientes;
        this.productos = productos;
        this.calificacion = calificacion;
    }
    public Calificacion(Integer id, Clientes clientes, Productos productos, Integer calificacion, String observacion) {
       this.id = id;
       this.clientes = clientes;
       this.productos = productos;
       this.calificacion = calificacion;
       this.observacion = observacion;
    }
   
     @Id 
    @GeneratedValue(strategy = IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clientes_id", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productos_id", nullable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

    
    @Column(name="calificacion", nullable=false)
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }

    
    @Column(name="observacion", length=100)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


