package com.enMedio.Model;
// Generated 18/07/2021 09:58:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Compras generated by hbm2java
 */
@Entity
@Table(name="compras"
    ,catalog="pruebaenmedio"
)
public class Compras  implements java.io.Serializable {


     private int id;
     private Productos productos;
     private String fecha;
     private String cantidad;

    public Compras() {
    }

	
    public Compras(int id, Productos productos) {
        this.id = id;
        this.productos = productos;
    }
    public Compras(int id, Productos productos, String fecha, String cantidad) {
       this.id = id;
       this.productos = productos;
       this.fecha = fecha;
       this.cantidad = cantidad;
    }
   
     @Id 
@GeneratedValue(strategy = IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productos_id", nullable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

    
    @Column(name="fecha", length=45)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="cantidad", length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }




}


