package com.enMedio.Model;
// Generated 18/07/2021 09:58:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name="productos"
    ,catalog="pruebaenmedio"
)
public class Productos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private double precioVenta;
     private double precioCompra;
     private String descripcion;
     private boolean estado;
     private Set productoventases = new HashSet(0);
     private Set calificacions = new HashSet(0);
     private Set comprases = new HashSet(0);

    public Productos() {
    }

	
    public Productos(int id, String nombre, double precioVenta, double precioCompra, boolean estado) {
        this.id = id;
        this.nombre = nombre;
        this.precioVenta = precioVenta;
        this.precioCompra = precioCompra;
        this.estado = estado;
    }
    public Productos(int id, String nombre, double precioVenta, double precioCompra, String descripcion, boolean estado, Set productoventases, Set calificacions, Set comprases) {
       this.id = id;
       this.nombre = nombre;
       this.precioVenta = precioVenta;
       this.precioCompra = precioCompra;
       this.descripcion = descripcion;
       this.estado = estado;
       this.productoventases = productoventases;
       this.calificacions = calificacions;
       this.comprases = comprases;
    }
   
     @Id 
@GeneratedValue(strategy = IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="precioVenta", nullable=false, precision=22, scale=0)
    public double getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(double precioVenta) {
        this.precioVenta = precioVenta;
    }

    
    @Column(name="precioCompra", nullable=false, precision=22, scale=0)
    public double getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(double precioCompra) {
        this.precioCompra = precioCompra;
    }

    
    @Column(name="Descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productos")
    public Set getProductoventases() {
        return this.productoventases;
    }
    
    public void setProductoventases(Set productoventases) {
        this.productoventases = productoventases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productos")
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productos")
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }

    @Column(name="estado", nullable=false)
    public boolean getEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    

}


