package com.enMedio.Model;
// Generated 18/07/2021 09:58:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ventas generated by hbm2java
 */
@Entity
@Table(name="ventas"
    ,catalog="pruebaenmedio"
)
public class Ventas  implements java.io.Serializable {


     private int id;
     private Clientes clientes;
     private Date fecha;
     private Long monto;
     private Long iva;
     private Long descuento;
     private Date fechaEntrega;
     private Set productoventases = new HashSet(0);

    public Ventas() {
    }

	
    public Ventas(int id, Clientes clientes) {
        this.id = id;
        this.clientes = clientes;
    }
    public Ventas(int id, Clientes clientes, Date fecha, Long monto, Long iva, Long descuento, Date fechaEntrega, Set productoventases) {
       this.id = id;
       this.clientes = clientes;
       this.fecha = fecha;
       this.monto = monto;
       this.iva = iva;
       this.descuento = descuento;
       this.fechaEntrega = fechaEntrega;
       this.productoventases = productoventases;
    }
   
     @Id 
@GeneratedValue(strategy = IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clientes_id", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="monto", precision=11, scale=0)
    public Long getMonto() {
        return this.monto;
    }
    
    public void setMonto(Long monto) {
        this.monto = monto;
    }

    
    @Column(name="iva", precision=11, scale=0)
    public Long getIva() {
        return this.iva;
    }
    
    public void setIva(Long iva) {
        this.iva = iva;
    }

    
    @Column(name="descuento", precision=11, scale=0)
    public Long getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Long descuento) {
        this.descuento = descuento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaEntrega", length=10)
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ventas")
    public Set getProductoventases() {
        return this.productoventases;
    }
    
    public void setProductoventases(Set productoventases) {
        this.productoventases = productoventases;
    }




}


